using UnityEditor;

namespace ExcelHeroes.EditorTools
{
    /// <summary>
    /// Card and UI art is generated by tools/gen-art.mjs and dropped straight into Resources, so it
    /// arrives with no import settings of its own. This pins what the game needs: sprites, no mip
    /// chain (everything is drawn 1:1 in UI Toolkit), and a size cap that keeps 55 portraits from
    /// eating the texture budget on a phone.
    ///
    /// Only applies on first import — re-importing by hand afterwards keeps whatever you changed.
    /// </summary>
    public class ArtImportSettings : AssetPostprocessor
    {
        const string ArtRoot = "Assets/ExcelHeroes/Resources/Art/";

        void OnPreprocessTexture()
        {
            if (!assetPath.StartsWith(ArtRoot)) return;
            var importer = (TextureImporter)assetImporter;
            if (!string.IsNullOrEmpty(importer.userData)) return;   // already configured once

            importer.textureType = TextureImporterType.Sprite;
            importer.spriteImportMode = SpriteImportMode.Single;
            importer.mipmapEnabled = false;
            importer.alphaIsTransparency = true;
            importer.maxTextureSize = 1024;
            importer.textureCompression = TextureImporterCompression.Compressed;
            importer.userData = "excel-heroes-art";
        }
    }
}
