# -*- coding: utf-8 -*-
"""
Draws the UI skin: the slanted button and panel shapes from the reference asset sheet.

WHY THIS EXISTS AND WHY IT IS NOT AI ART
----------------------------------------
The reference's buttons are parallelograms — both vertical edges slant — with a white rim, a
diagonal highlight across the top-left, and a gold triangle biting one corner. USS cannot express
any of that: it has `rotate`, `scale` and `translate` but NO skew, so a slanted edge is not a
property you can set. The shape has to arrive as a picture.

Everything here is geometry: polygons, gradients and a blur, drawn with PIL from numbers in this
file. Nothing is generated by a model and nothing is traced from the reference — the handoff's
"do not generate art" rule is about the character illustrations, and this is the opposite of that
situation, a deterministic script whose output can be regenerated byte for byte.

HOW THE SHAPES SURVIVE BEING STRETCHED
--------------------------------------
Each button is one PNG, sliced horizontally: a fixed left cap carrying the slant, a one-pixel
middle that stretches to whatever the label needs, and a fixed right cap. That is why the caps are
drawn at full height and the middle is flat — a 9-slice cannot stretch a diagonal without shearing
it, so the diagonals live only in the caps.

    python tools/gen-ui-skin.py

Output: Assets/ExcelHeroes/Art/UI/*.png, and the slice widths printed for App.uss.

NOTE: the BUTTON plates used to be baked here too and are not any more — SkewPlate paints them
from a mesh, which has no cap budget and keeps one slant angle at every size. What is left is the
panel caption bar, whose slant is at one end only and whose height never varies, so a 9-slice is
the simpler answer for it.
"""
import os
from PIL import Image, ImageDraw, ImageFilter

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   '..', 'Assets', 'ExcelHeroes', 'Art', 'UI')
OUT = os.path.normpath(OUT)

# Drawn at 4x and downsampled, because PIL has no anti-aliasing of its own and a 20-degree edge
# drawn at 1x is a staircase.
SS = 4

H = 120           # the tap height the UI uses, so a button is pixel-exact at its natural size
SLANT = 26        # horizontal run of the slanted edge
# The fixed slice has to be wide enough to hold EVERY decoration, because anything that crosses
# into the middle gets stretched with it. The first cut of this was SLANT + 26 and both the gold
# notch and the highlight ran past it, so a stretched button came out with a gold bar down its
# whole top edge and a smear where the streak should have been.
CAP = SLANT + 62
W = CAP * 2 + 2   # two caps and a two-pixel stretchable middle
RIM = 5           # the white rim
GOLD = (255, 205, 60, 255)


def poly(d, pts, fill):
    d.polygon([(x * SS, y * SS) for x, y in pts], fill=fill)


def body(inset):
    """The parallelogram, pulled in by `inset` on every side."""
    s = SLANT
    return [
        (s + inset, inset),
        (W - inset, inset),
        (W - s - inset, H - inset),
        (inset, H - inset),
    ]


def vertical_gradient(size, top, bottom):
    g = Image.new('RGBA', size)
    d = ImageDraw.Draw(g)
    for y in range(size[1]):
        t = y / max(1, size[1] - 1)
        d.line([(0, y), (size[0], y)],
               fill=tuple(int(top[i] + (bottom[i] - top[i]) * t) for i in range(4)))
    return g


def button(name, top, bottom, rim=(255, 255, 255, 255), gold_corner='tl', sheen=0.30):
    big = (W * SS, H * SS)
    img = Image.new('RGBA', big, (0, 0, 0, 0))
    d = ImageDraw.Draw(img)

    # The rim first, as a solid parallelogram; the fill is drawn inside it.
    poly(d, body(0), rim)

    fill = vertical_gradient(big, top, bottom)
    mask = Image.new('L', big, 0)
    poly(ImageDraw.Draw(mask), body(RIM), 255)
    img.paste(fill, (0, 0), mask)

    # The diagonal highlight. In the sheet it is a CRISP band running parallel to the slanted
    # edges, not a soft cloud — a blurred blob reads as a smudge on the plate rather than as a
    # reflection across glass. So: hard polygon, a single pixel of blur to take the staircase off,
    # and clipped to the fill so it never touches the rim.
    if sheen > 0:
        sheen_layer = Image.new('RGBA', big, (0, 0, 0, 0))
        sd = ImageDraw.Draw(sheen_layer)
        a = int(255 * sheen)
        # Two bands, both entirely inside the LEFT cap. Measured along the top edge, the cap ends
        # at SLANT + CAP, so the widest band plus its offset has to stay under that.
        for x0, w0, mul in ((RIM + 3, 30, 1.0), (RIM + 39, 11, 0.55)):
            assert x0 + w0 <= CAP - 4, 'highlight would cross the slice boundary'
            sd.polygon([(px * SS, py * SS) for px, py in [
                (SLANT + x0, RIM),
                (SLANT + x0 + w0, RIM),
                (x0 + w0, H - RIM),
                (x0, H - RIM),
            ]], fill=(255, 255, 255, int(a * mul)))
        sheen_layer = sheen_layer.filter(ImageFilter.GaussianBlur(SS // 2))
        clipped = Image.composite(sheen_layer.split()[3], Image.new('L', big, 0), mask)
        img.paste(Image.new('RGBA', big, (255, 255, 255, 255)), (0, 0), clipped)

    # The gold corner. In the sheet it sits on one end only and is what keeps a row of buttons
    # from reading as a row of identical slabs.
    gd = ImageDraw.Draw(img)
    NOTCH = 44          # stays well inside CAP, which is what stops it stretching into a bar
    if gold_corner == 'tl':
        poly(gd, [(SLANT, 0), (SLANT + NOTCH, 0), (SLANT + NOTCH - 12, 15), (SLANT - 7, 15)], GOLD)
    elif gold_corner == 'br':
        poly(gd, [(W - SLANT - NOTCH + 12, H - 15), (W - SLANT + 7, H - 15),
                  (W - SLANT, H), (W - SLANT - NOTCH, H)], GOLD)

    img = img.resize((W, H), Image.LANCZOS)
    path = os.path.join(OUT, name + '.png')
    img.save(path)
    return path


def panel_head(name, top, bottom, accent=GOLD, slant=20, h=56, cap_l=30):
    """
    The sheet's panel caption: a navy bar whose RIGHT end is cut at an angle, with a bright stripe
    down the left. Left-aligned, unlike the plain centred band this replaces — the sheet's captions
    start where the content starts, so the eye finds the top-left corner of a block instead of its
    middle.

    Sliced with different caps at each end: the left holds the stripe, the right holds the slant.
    """
    cap_r = slant + 18
    w = cap_l + cap_r + 2
    big = (w * SS, h * SS)
    img = Image.new('RGBA', big, (0, 0, 0, 0))
    d = ImageDraw.Draw(img)

    shape = [(0, 0), (w, 0), (w - slant, h), (0, h)]
    d.polygon([(x * SS, y * SS) for x, y in shape], fill=(255, 255, 255, 255))

    fill = vertical_gradient(big, top, bottom)
    mask = Image.new('L', big, 0)
    ImageDraw.Draw(mask).polygon(
        [(x * SS, y * SS) for x, y in [(2, 2), (w - 2, 2), (w - slant - 2, h - 2), (2, h - 2)]], 255)
    img.paste(fill, (0, 0), mask)

    # The stripe, entirely inside the left cap so it cannot stretch.
    if accent:
        assert 12 <= cap_l - 4, 'accent would cross the slice boundary'
        ImageDraw.Draw(img).rectangle([2 * SS, 2 * SS, 12 * SS, (h - 2) * SS], fill=accent)

    img = img.resize((w, h), Image.LANCZOS)
    path = os.path.join(OUT, name + '.png')
    img.save(path)
    print('   slice-left %d  slice-right %d   (%s, %dx%d)' % (cap_l, cap_r, name, w, h))
    return path


def main():
    os.makedirs(OUT, exist_ok=True)

    made = [

        panel_head('panel_head', (46, 72, 116, 255), (26, 42, 74, 255)),
    ]

    for p in made:
        print('  ', os.path.relpath(p, os.path.join(OUT, '..', '..', '..', '..')))
    print()
    print('  slice-left / slice-right = %d   (natural size %dx%d)' % (CAP, W, H))


if __name__ == '__main__':
    main()
